// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

/************************************************************/
/**
 * 
 */
public class Horca {
	protected static final int MAX_FALLOS = 6;
	/**
	 * es el número de fallos que lleva el usuario, vamos a permitir 6 fallos
	 */
	private int fallos;

	/**
	 * @return the fallos
	 */
	public int getFallos() {

	}

	public Horca() {

	}

	/**
	 * 
	 */
	public void dibujar() {

	}

	/**
	 * incrementa el contador de fallos
	 */
	public void incrementarFallo() {

	}

	/**
	 * comprueba si hemos perdido la partida
	 * 
	 * @return perdido
	 */
	public boolean comprobarSiPerdido() {

	}
}
