// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

/************************************************************/
/**
 * 
 */
public class Palabra {

	private static final int NUM_LETRAS_ABECEDARIO = 27;
	/**
	 * 
	 */
	private String palabraOculta;
	/**
	 * son las letras que el jugador ha acertado
	 */
	private char[] letrasDescubiertas = new char[NUM_LETRAS_ABECEDARIO];
	/**
	 * son las letras que el jugador ha dicho pero no estaban en la palabra
	 */
	private char[] letrasFallidas = new char[NUM_LETRAS_ABECEDARIO];

	/**
	 * 
	 */
	public void elegirPalabra() {

	}

	/**
	 * Comprueba si la letra ya ha sido usada.
	 */
	public boolean comprobarLetraUsada(char letra) {

	}

	/**
	 * comprueba si letra está en la palabra oculta (no comprueba si la letra ha
	 * sido usada) y la almacena como acertada o fallida.
	 * 
	 * @param letra
	 *            es la letra a comprobar si está en la palabra a adivinar
	 * @return estaba devuelve verdadero si la letra está al menos una vez en la
	 *         palabra y falso en caso contrario
	 */
	public boolean comprobarLetra(char letra) {

		
	}

	/**
	 * 
	 * @param letra
	 *            Letra insertada por el usuario
	 * @param destino
	 *            Guarda la letra insertada por el usuario.
	 */

	private void insertarLetra(char letra, char[] destino) {

	}

	/**
	 * mostramos el estado de la palabra, las letras acertadas y las letras
	 * fallidas
	 */
	public void mostrarResultados() {

	}

	/**
	 * comprueba si hemos acertado todas las letras
	 * 
	 * @return ganado
	 */
	public boolean comprobarSiGanado() {

	}

	/**
	 * comprueba si la palabra propuesta por el jugador coincide con la palabra
	 * oculta (quiero resolver)
	 * 
	 * @param palabra
	 * @return adivinada adivinada es verdadero si la palabra coincide con la
	 *         que buscábamos
	 */
	public boolean comprobarPalabra(String palabra) {

	}
}
