// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Ahorcado;

import java.util.Scanner;

import com.sun.corba.se.spi.resolver.Resolver;

import Ahorcado.Horca;
import Ahorcado.Palabra;
import sun.applet.Main;

/************************************************************/
/**
 * 
 */
public class Partida {
	/**
	 * 
	 */
	public static Palabra palabra;
	/**
	 * 
	 */
	public static Horca horca;

	/**
	 * Muestra el estado de la horca y los resultados de palabra
	 */
	public static void mostrarProgreso() {

	}

	/**
	 * Solicita una letra al usuario
	 * 
	 * @return letra
	 */
	public static char pedirLetra() {

	}

	/**
	 * Pide la respuesta
	 * 
	 * @return palabra true si era la que buscábamos o false en caso contrario
	 */
	public static boolean resolver() {

	}

	/**
	 * Comprueba tanto si hemos agotado los fallos como si hemos acertado todas
	 * las letras
	 * 
	 * @return fin
	 */
	public static boolean comprobarFinal() {

	}

	public static int elegirDelMenu() {

	}

	public static void main(String[] args) {

	}

}
